version: '3.8'

services:
  mysql:
    # build: 
    #   context: ./db
    #   dockerfile: mysql.dockerfile
    image: mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - ./db/leftoverkiller_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  nodejs:
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "mysql"
    links:
      - mysql:mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge