# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm i --force

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which your app runs
EXPOSE 3001

# Command to run your app
CMD ["npm", "start"]
